/*
 * Created By Jong Ho, Lee on  2020.
 * Copyright 테크하임(주). All rights reserved.
 */

package x.com.nubextalk.Module.FaFont;

import com.joanzapata.iconify.Icon;

public enum IconsFAR implements Icon {

    far_address_book('\uf2b9'),
    far_address_card('\uf2bb'),
    far_angry('\uf556'),
    far_arrow_alt_circle_down('\uf358'),
    far_arrow_alt_circle_left('\uf359'),
    far_arrow_alt_circle_right('\uf35a'),
    far_arrow_alt_circle_up('\uf35b'),
    far_bell('\uf0f3'),
    far_bell_slash('\uf1f6'),
    far_bookmark('\uf02e'),
    far_building('\uf1ad'),
    far_calendar('\uf133'),
    far_calendar_alt('\uf073'),
    far_calendar_check('\uf274'),
    far_calendar_minus('\uf272'),
    far_calendar_plus('\uf271'),
    far_calendar_times('\uf273'),
    far_caret_square_down('\uf150'),
    far_caret_square_left('\uf191'),
    far_caret_square_right('\uf152'),
    far_caret_square_up('\uf151'),
    far_chart_bar('\uf080'),
    far_check_circle('\uf058'),
    far_check_square('\uf14a'),
    far_circle('\uf111'),
    far_clipboard('\uf328'),
    far_clock('\uf017'),
    far_clone('\uf24d'),
    far_closed_captioning('\uf20a'),
    far_comment('\uf075'),
    far_comment_alt('\uf27a'),
    far_comment_dots('\uf4ad'),
    far_comments('\uf086'),
    far_compass('\uf14e'),
    far_copy('\uf0c5'),
    far_copyright('\uf1f9'),
    far_credit_card('\uf09d'),
    far_dizzy('\uf567'),
    far_dot_circle('\uf192'),
    far_edit('\uf044'),
    far_envelope('\uf0e0'),
    far_envelope_open('\uf2b6'),
    far_eye('\uf06e'),
    far_eye_slash('\uf070'),
    far_file('\uf15b'),
    far_file_alt('\uf15c'),
    far_file_archive('\uf1c6'),
    far_file_audio('\uf1c7'),
    far_file_code('\uf1c9'),
    far_file_excel('\uf1c3'),
    far_file_image('\uf1c5'),
    far_file_pdf('\uf1c1'),
    far_file_powerpoint('\uf1c4'),
    far_file_video('\uf1c8'),
    far_file_word('\uf1c2'),
    far_flag('\uf024'),
    far_flushed('\uf579'),
    far_folder('\uf07b'),
    far_folder_open('\uf07c'),
    far_frown('\uf119'),
    far_frown_open('\uf57a'),
    far_futbol('\uf1e3'),
    far_gem('\uf3a5'),
    far_grimace('\uf57f'),
    far_grin('\uf580'),
    far_grin_alt('\uf581'),
    far_grin_beam('\uf582'),
    far_grin_beam_sweat('\uf583'),
    far_grin_hearts('\uf584'),
    far_grin_squint('\uf585'),
    far_grin_squint_tears('\uf586'),
    far_grin_stars('\uf587'),
    far_grin_tears('\uf588'),
    far_grin_tongue('\uf589'),
    far_grin_tongue_squint('\uf58a'),
    far_grin_tongue_wink('\uf58b'),
    far_grin_wink('\uf58c'),
    far_hand_lizard('\uf258'),
    far_hand_paper('\uf256'),
    far_hand_peace('\uf25b'),
    far_hand_point_down('\uf0a7'),
    far_hand_point_left('\uf0a5'),
    far_hand_point_right('\uf0a4'),
    far_hand_point_up('\uf0a6'),
    far_hand_pointer('\uf25a'),
    far_hand_rock('\uf255'),
    far_hand_scissors('\uf257'),
    far_hand_spock('\uf259'),
    far_handshake('\uf2b5'),
    far_hdd('\uf0a0'),
    far_heart('\uf004'),
    far_hospital('\uf0f8'),
    far_hourglass('\uf254'),
    far_id_badge('\uf2c1'),
    far_id_card('\uf2c2'),
    far_image('\uf03e'),
    far_images('\uf302'),
    far_keyboard('\uf11c'),
    far_kiss('\uf596'),
    far_kiss_beam('\uf597'),
    far_kiss_wink_heart('\uf598'),
    far_laugh('\uf599'),
    far_laugh_beam('\uf59a'),
    far_laugh_squint('\uf59b'),
    far_laugh_wink('\uf59c'),
    far_lemon('\uf094'),
    far_life_ring('\uf1cd'),
    far_lightbulb('\uf0eb'),
    far_list_alt('\uf022'),
    far_map('\uf279'),
    far_meh('\uf11a'),
    far_meh_blank('\uf5a4'),
    far_meh_rolling_eyes('\uf5a5'),
    far_minus_square('\uf146'),
    far_money_bill_alt('\uf3d1'),
    far_moon('\uf186'),
    far_newspaper('\uf1ea'),
    far_object_group('\uf247'),
    far_object_ungroup('\uf248'),
    far_paper_plane('\uf1d8'),
    far_pause_circle('\uf28b'),
    far_play_circle('\uf144'),
    far_plus_square('\uf0fe'),
    far_question_circle('\uf059'),
    far_registered('\uf25d'),
    far_sad_cry('\uf5b3'),
    far_sad_tear('\uf5b4'),
    far_save('\uf0c7'),
    far_share_square('\uf14d'),
    far_smile('\uf118'),
    far_smile_beam('\uf5b8'),
    far_smile_wink('\uf4da'),
    far_snowflake('\uf2dc'),
    far_square('\uf0c8'),
    far_star('\uf005'),
    far_star_half('\uf089'),
    far_sticky_note('\uf249'),
    far_stop_circle('\uf28d'),
    far_sun('\uf185'),
    far_surprise('\uf5c2'),
    far_thumbs_down('\uf165'),
    far_thumbs_up('\uf164'),
    far_times_circle('\uf057'),
    far_tired('\uf5c8'),
    far_trash_alt('\uf2ed'),
    far_user('\uf007'),
    far_user_circle('\uf2bd'),
    far_window_close('\uf410'),
    far_window_maximize('\uf2d0'),
    far_window_minimize('\uf2d1'),
    far_window_restore('\uf2d2');

    char character;

    IconsFAR(char character) {
        this.character = character;
    }

    @Override
    public String key() {
        return name().replace('_', '-');
    }

    @Override
    public char character() {
        return character;
    }
}
